### ISSUE TITLE
Make players visible after joined game

### ISSUE THREAD

**Issue by jilleJr** [jilleJr/TellMe#14]
Some basic list.

Both when hosting and joining a game.

Should auto update on players joining and leaving.

**Comment by Alexamakans** [comment]
Working on this in [feature/host-player-list](https://github.com/jilleJr/TellMe/tree/feature/host-player-list).
Unable to test though due to being able to use the multiplayer services from a built version:
![no-bueno](https://user-images.githubusercontent.com/79503481/153776905-5ae6d4b3-eead-4051-bf8e-53a87dad345d.png)

**Comment by jilleJr** [comment]
This was closed in #19
